property_positive:
  name: 'Filter 1'
  category: 'Transports'
  sub_categories:
    - sub_category:
      title: 'Transports'
      option: 'Vieglie auto'
    - sub_category:
      title: 'Vieglie auto'
      option: 'Audi'
    - sub_category:
      title: 'Audi'
      option: 'Audi A4'
    - sub_category:
      title: 'Darbība'
      option: 'Visi'
  parameters:
    - parameter:
      name: 'CENA (EUR)'
      left: '1'
      right: '1000'

property_negative:
  name: 'Filter 2'
  category: 'Transports'
  sub_categories:
    - sub_category:
      title: 'Transports'
      option: 'Vieglie auto'
    - sub_category:
      title: 'Vieglie auto'
      option: 'Audi'
    - sub_category:
      title: 'Audi'
      option: 'Audi A3'
    - sub_category:
      title: 'Darbība'
      option: 'Visi'
  parameters:
    - parameter:
      name: ''
      left: ''
      right: ''

